### PR TITLE
fixing missing verification of client response type and encoding the client secret

### PR DESCRIPTION
**Pull request by wojtek-fliposports**

### CODE REVIEW

**Comment by juanifioren** [comment]
Ok, but now the framework supports OAuth2 request. So what if a client wants to make both openid and oauth2 requests. As it only can add one response type.

**Comment by wojtek-fliposports** [comment]
so how "response type" can be checked now ?

**Comment by juanifioren** [comment]
Oh sorry, didn't see that you also check if it's an OpenID request (`self.is_authentication`). Wouldn't be a problem!

**Comment by wojtek-fliposports** [comment]
This was security volnurealibility. Can You deply new version ?

**Comment by juanifioren** [comment]
@wojtek-fliposports ready!

**Comment by wojtek-fliposports** [comment]
thanks :)

**Pull request merged**
