### PR TITLE
Add token introspection endpoint

### PR DESCRIPTION
**Pull request by mdaniline**
Add a token introspection endpoint to satisfy https://tools.ietf.org/html/rfc7662

We define a new swappable model `Resource`. This model is then used to authorize a request to the token introspection endpoint via either a `Basic` auth header or `client_id`/`client_secret` post parameters. It is also possible to configure exactly which `Client` instances are allowed to access a given `Resource`.

The id/secret are stored as plain text as:
* It is reasonable for a resource owner to pass these to client owners without having to recreate them afresh.
* The endpoint is useless without a valid `token`.

It is possible to customise the valid response as well as the `Resource` model itself, as the current implementation is fairly basic.

### CODE REVIEW

**Comment by juanifioren** [comment]
Thanks for the MR. I don't get the Resource model part. Is really necessary for the introspection feature?.

**Comment by mdaniline** [comment]
It is not strictly required, but it a sensible way of allowing clients access to specific APIs (resources) on a per-client basis. This is the purpose of the `allowed_clients` M2M field on the `Resource` model. For reference, the logic which makes use of this is on line 59 of `introspection.py`.
Let me know if you want a more concrete example :)

**Comment by juanifioren** [comment]
@mdaniline Could you separate the Resource model from the instrospection feature? I'm thinking merging this. But don't want to mess the roadmap of the project. Sorry for this

**Comment by mdaniline** [comment]
@juanifioren I can do, but what do you suggest as the default authentication mechanism for the calling resource?

**Comment by juanifioren** [comment]
Let's use client credentials using HTTP Basic Authentication method.

I refactor code on `develop` so now you can extract client auth form request (was attached to token endpoint before).
https://github.com/juanifioren/django-oidc-provider/blob/develop/oidc_provider/lib/utils/oauth2.py#L32

**Comment by juanifioren** [comment]
Then validation could be like:
https://github.com/juanifioren/django-oidc-provider/blob/develop/oidc_provider/lib/endpoints/token.py#L54:L64

**Comment by juanifioren** [comment]
Yup, I was thinking somethin like this.
https://connect2id.com/products/server/docs/api/token-introspection

Client credentials grant was released on last version so should be easy to implement.

**Comment by juanifioren** [comment]
The side effect of this implementation is that client MUST have a "token_instrospection" scope registered for him.

**Comment by mdaniline** [comment]
OK, that is a good plan. I'll look into it

**Comment by mdaniline** [comment]
Done. I've added an extra feature (which can be disabled) of using the client ID as a scope in order to be able to restrict access to resources on a per-client basis.

**Comment by mdaniline** [comment]
Sorry, forgot about the settings documentation. All good now!

**Comment by mdaniline** [comment]
I've made those changes locally; I can't commit because of network restrictions today (don't ask...) so I'll do so tomorrow. Code coverage is 91% both in the master branch and in the PR.

**Comment by juanifioren** [comment]
@mdaniline Great so! waiting for them so we merge and close this :drum:

**Comment by mdaniline** [comment]
Done

**Pull request merged**
