### PR TITLE
Support for at_hash

### PR DESCRIPTION
**Pull request by brosner**
This PR adds support for access token validation by providing `at_hash`. This is required for the `id_token token` response type. Other response types can use `at_hash` but is optional.

http://openid.net/specs/openid-connect-core-1_0.html#ImplicitIDToken

### CODE REVIEW

**Comment by juanifioren** [comment]
Awesome! Testing... Btw, do you think we should add some kind of documentation of this feature inside `docs/` folder?

**Comment by grahamu** [comment]
@juanifioren First, thanks so much for writing such a useful package! Your code simplifies the OIDC workflow immensely.

How did your testing of our PR go? Locally (for me) detox passed all configurations, all tests. Speaking of testing, is there any chance you might enable Travis builds for pull requests? That way we would know if a submitted PR is failing. Thanks!

As for documentation, this PR does not add a "feature" so much as it fixes django-oidc-provider so that implicit flow with "id_token token" request type works properly. The requirement for `at_hash` is documented in the OIDC specification mentioned by Brian above. So I don't believe django-oidc-provider needs additional documentation.

I have personally tested this PR using https://github.com/IdentityModel/oidc-client-js, in fact that's how I found the problem, it complained about `no at_hash in id_token`. With this fix in place no error appears and the id and access tokens are valid.

**Comment by juanifioren** [comment]
Cool. Thanks for clearing it out. PR with Travis are active now (my fault!). Tomorrow I'll do the merge.

**Comment by grahamu** [comment]
Thanks @juanifioren, for your timely review and for activating Travis. Cheers!

**Comment by juanifioren** [comment]
Hi guys, @grahamu @brosner 

I have a question about the `runtests.py` file. Now we can remove the `oidc_provider.tests.app.settings.py` file?. Because settings are replicated on both files.

What about `tox.ini` and `.travis.yml`? Can we just run it without passing the settings parameter?.
Thanks.

**Comment by grahamu** [comment]
@juanifioren I'm creating a new PR for improved test setup that will address your questions.

**Pull request merged**
