### PR TITLE
Made token and token_refresh endpoint return requested claims.

### LINKED ISSUE #214: id_token doesn't include claims
I've spent significant time on this and am now pretty sure there is an error causing no additional claims to be returned in the JWT when additional scopes (e.g. email, profile) are requested. 

Steps to reproduce (authorization code flow):

Requests authorization code with scopes 'idtoken email profile'

Use the code, client_id and client_secret with the same scopes to fetch the access token, id_token and refresh token.

Notice that in the resulting id_token there is no claims for email_verified, name or the like. 

I thought this was because I was using the OIDC_USERINFO setting wrong, but when the /token endpoint is hit this setting is never fetched and the respective function never called. 

My particular use-case is that I want to use OpenID Connect to connect to Kubernetes with the oidc authentication method. The Kubernetes API server checks for the email-verified claim in the id_token and errors if it is not found.

### PR DESCRIPTION
**Pull request by dhrp**
This PR makes a change such that the id_token returned from the /token endpoint, during the  authorization code flow return an id_token with the requested claims. This works for token and refresh_token.

closes #214

Amongst other things, this makes it possible to use django_oidc_provider as an identity provider for Kubernetes RBAC

### CODE REVIEW

**Comment by dhrp** [comment]
Please let me know if you have any comments.

**Comment by wojtek-fliposports** [comment]
checking

**Comment by dhrp** [comment]
Hmmm. I see your point about how other users may have extended ScopClaim, expecting a 'token'. The issue I had was that ` def create_id_token(user, aud, nonce='', at_hash='', request=None, scope=[]):` Doesn't have access to the token. I could make a little dict with the user, scopes and  client properties, that would work.  I'll update it that way. 

-- Couldn't find any use of 'client' btw. 

https://github.com/juanifioren/django-oidc-provider/pull/220/files#diff-3c6b3df6e2c27dac5d4f6125672013cfR22

And well spotted on the userinfo endpoint not updating that was an error

**Comment by dhrp** [comment]
and I'll rebase on the develop branch.

**Comment by dhrp** [comment]
Ok, so in the last commit I've passed the token along into the create_id_token function.  I feel this makes sense because the Token object is normally already created. It did mean, however that I had to edit a couple of tests.

An alternative would be to recreate a fake token dict, just to pass into ScopeClaims.

**Comment by dhrp** [comment]
ping?

**Comment by wojtek-fliposports** [comment]
sorry, I will look at it in this week - sorry

**Pull request merged**
