### PR TITLE
WIP 🚧 | More extendability

### PR DESCRIPTION
**Pull request by stefanfoulis**
# 🚧 Work in progress - Do not merge yet 🚧

Initially I wanted to make all models swappable. That did not work out. Here is a backup of the failed attempt: https://github.com/stefanfoulis/django-oidc-provider/pull/1

# How to review

Review commit-by-commit and read the commit messages.

# What has been added and changed

## Customizeable `Code`, `Token` and `UserConsent`

`create_token`, `create_code` and `update_or_create_user_consent` are used to create the `Token`, `Code` and `UserConsent` models. They are now user overridable functions that include some important context (`request`) that is useful for customisation.

### Saving additional information

A possible customisation could be to save additional information with these models, like which device the user was using when he requested the `access_token`. An additional model with a `OneToOne` relationship to `Token` could be added to store that information and `create_token` could be overridden to save it at token creation time.

`settings.py`:
```python
OIDC_CREATE_TOKEN='myapp.my_create_token_with_extra_context'
```
`models.py`:
```python
class TokenContext(models.Model):
	token = models.OneToOneField(Token, primary_key=True, on_delete=models.CASCADE, related_name='context')
	device = models.ForeignKey(Device, on_delete=models.CASCADE)
	user_agent = models.TextField(blank=True)
```
```python
def my_create_token_with_extra_context(**kwargs):
    token = default_create_token(**kwargs)
	TokenContext.objects.create(
		token=token,
		device=get_device_from_request(kwargs['request']),
		user_agent=get_ua_from_request(kwargs['request']),
	)
    return token
```

### Custom `JWT` `access_token`
`settings.py`:
```python
OIDC_CREATE_TOKEN='myapp.my_create_jwt_token'
```
```python
def my_create_jwt_token(**kwargs):
    kwargs['access_token'] = create_my_jwt_token(kwargs['user'], kwargs['scope'], kwargs['request'])
    return default_create_token(**kwargs)
```

### Customize expiration based on scopes
`settings.py`:
```python
OIDC_CREATE_TOKEN='myapp.my_custom_token_with_customized_expiration'
```
```python
def my_custom_token_with_customized_expiration(**kwargs):
    kwargs['expires_at'] = calculate_expiration(kwargs['scope'])
    return default_create_token(**kwargs)
```

- [x] Check if that actually works everywhere. I think there are some places where we return the setting instead of the value from the stored token. -- **fixed**

## Remove `ResponseType` model

The allowed response types of a `Client` used to be saved in a database table even though the list of choices is static. This change turns response_types into a `TextField` (with JSON inside) instead of a relation. In admin, it is displayed as a list of checkboxes.

screenshot 2018-12-18 at 00 25 15

This one does not really fit in this PR. I made the change because of troubles I had with swappable models - an idea I later abandoned.
If required I could make this a separate PR, but I'll have to fiddle with the migrations.

## Revert swappable Client model

I realized that swappable models are not a maintenance burden we should add to the project because it adds complexity and tricky-ness to the project. It will also not be possible to make multiple models swappable because that does not work if they have relations.
In most cases where one might want to swap the model the same can be achieved with a new model and a OneToOne relationship to the model one wants to extend.
So this commit reverts the swappable `Client` model PR that was already merged into `develop`.

## Support for tokens larger than `255` chars

To facilitate that a `JWT` `access_token` might now be larger than `255` characters (the limit on the old token field), there are now two fields per token:
- `access_token`: a `TextField` with the full token. It is not indexed, because not all database backends support indexing `TextField` and indexing large fields is expensive.
- `access_token_hash`: the `sha256` hash of the token in an indexed `CharField`. This is used to efficiently fetch the token from the db.

# Todo

- [x] Allow overriding the endpoint class easily when subclassing the views
- [x] Custom function to generate access_token and refresh_token
- [x] Revert swappable `Client` model (originally added in #305)
- [x] efficient lookup for large access keys (JWT) -- use hash of token as lookup key

- Customizable model creation and important actions
  - [x] `create_token()` (include `request`)
  - [x] `create_code()` (include `request`)
  - [x] `update_or_create_user_consent()` (include `request`)
  - [x] `get_login_url()` (include `client` and `request`)

- [ ] Rebase on current `develop` (because the swappable Client PR was reverted)

- [ ] More tests

- Write Docs:
  - [ ] update screenshot with new response_types widget
  - how to extend:
    - [ ] adding fields to models (use OneToOne table)
    - [ ] Customizing the access token (e.g JWT)
    - [ ] dynamic login url redirects based on `Client`
    - [ ] ...

- [ ] Merge migrations

### CODE REVIEW

**Comment by stefanfoulis** [comment]
I've had little progress trying to make all the models swappable. It looks like it is not possible to have a swappable model have a relationship with another swappable model in the same app. There are hacks to get it to work, but we'd have to put the `Client` model into a different app than the rest of the models. I'm not sure if it really would work though. And that would be way too much special stuff just for model swap-ability.
I'm pondering on how to solve this.

**Comment by stefanfoulis** [comment]
I got the very basics to work to swap `Code`, `Token` and `UserConsent` (not pushed to github yet), but I had to remove the swap-ability of `Client`.
My current thinking is that offering swappable models is not worth the complexity it introduces. Instead, we could improve other extension points. I suspect most situations where someone would want to swap a model could also be solved by a custom model with a `OneToOne` relationship to the original model.
But it's late and my head hurts. I'll think about this more later.

**Comment by stefanfoulis** [comment]
@juanifioren what do you think? I'd love to have a chat to discuss the changes and figure out if this is the direction you want to go in.

**Comment by juanifioren** [comment]
Sorry. I must close this since is adding lot of changes.

**Comment by stefanfoulis** [comment]
@juanifioren I'll make individual PRs with smaller changes at some point, but I don't know yet when I'll get around to it.

**Pull request closed without merging**
