### PR TITLE
Improve CI testing configuration

### PR DESCRIPTION
**Pull request by grahamu**
Minor updates for CI testing:

* Improve tox.ini envlist layout, simplify commands. Also remove "stats" since `coverage report -m` was not working.
* Remove tests/app/settings.py in favor of settings in setup.py.
* Change MANIFEST.in to include README.md (which exists) instead of README.rst (which does not exist).
* Update .travis.yml to use tox instead of `python django_admin.py`, include Django v1.10 in the mix.
* Update django-oidc-provider version to 0.3.7 (after `at_hash` fix).

Hopefully you will release version 0.3.7 to PyPi with the `at_hash` fix and updated testing configuration. Thanks!

### CODE REVIEW

**Comment by juanifioren** [comment]
I think the error is because the env should be `py27-django17` instead of `py27-django1.7`.

**Comment by juanifioren** [comment]
Fixed and merged. Thanks for that great contribution.

**Comment by grahamu** [comment]
You're welcome Juan. Travis build looks good!

**Comment by juanifioren** [comment]
Btw, now this command doesn't work (to run single test file):
```
tox -e py27-django19 oidc_provider.tests.test_authorize_endpoint
```
Was trying to see how to fix it but no success. Any hints to solve this?. Thanks.

**Pull request merged**
