### PR TITLE
JWT deps support for pyjwkest and python-jose

### PR DESCRIPTION
**Pull request by jdunck**
I haven't been able to keep requirements-file compat. That is, install with pyjwkest is now 'pip install django-oidc-provider[pyjwkest]' rather than 'pip install django-oidc-provider'. Otherwise, this PR has tests passing in all tox environments (have a look at diff in setup.py and tox.ini).

Given the change in install, I think maybe this would make 0.4.0? Feedback welcome. :)

### CODE REVIEW

**Comment by jdunck** [comment]
@juanifioren  OK, how about this one? ;-)

**Comment by juanifioren** [comment]
Thanks! sorry for bothering. Just trying to keep branchs safe haha. I'll be with this soon.

**Comment by jdunck** [comment]
@juanifioren I will be mostly offline for a week, so please don't take my slow response as lack of interest.  I'll check email but be unable to make code changes for the week.

**Comment by juanifioren** [comment]
No problem @jdunck. Thanks for your contribution btw. This should be added soon.
Greetings.

**Comment by jdunck** [comment]
Hi @juanifioren - do you think this will make 0.4?

**Comment by juanifioren** [comment]
Hi @jdunck 
I'll merge `v0.4.x` into `feature-jwtdeps` so we can update code. But we need a way to have a default package (should be pyjwkest). So `pip install django-oidc-provider` has `pyjwkest` with it.

**Comment by jdunck** [comment]
OK, I've looked around at `setup(extra_requires)` and don't see a way to specify pyjwkest as default if no "extra" is specified.  So the best alternative I can see would be to have 2 `setup.py` files which specifify different `install_requires`, and a little wrapper script to rename and register them with pypi (as 2 different packages).  django-oidc-provider and django-oidc-provider-jose, maybe.   Which... yuck.

I wish there were a way to specify a default implementation and allow the "extra" to override it, like kwargs with defaults.

**Comment by juanifioren** [comment]
What do you think about leaving `setup.py` just with

```python
...
install_requires=[
    'pyjwkest==1.1.0',
],
```

And then provide documentation that you can `pip uninstall pyjwkest` and `pip install python-jose` if you want to use jose lib. So I think everything should work as normal, as you create the fallback imports for both libs. I know is not the best solution, but at least you have the solution for the dependencies problem.

**Comment by jdunck** [comment]
Unfortunately that doesn't address our issue - we have transitive dependencies on PyCrypto and PyCryptodome right now.  Since those share the same namespace (both importable under Crypto), they "damage" each other when installed together, depending on the order of install.    Also, uninstalling pyjwkest wouldn't uninstall its transitives.   What's really needed here is the equivalent of debian 'virtual packages', but of course pip etc don't support that.

We need better control over transitive dependencies - which I'm hoping to achieve with this branch.  (The alternative is islands of libraries which depend on different incompatible crypto deps, which is sad.)

I guess you find the 2-setup.py-files approach too smelly.  I can't blame you, but I haven't heard of a better solution. :/

**Comment by jdunck** [comment]
I did just have a thought, right after I hit the comment button.

We could make the setup.py change `install_requires` based on whether it can import `jose`.

```python
try:
   import jose
except ImportError:
   install_requires = ['pyjwkest>=...']
else:
   install_requires = ['python-jose>=...']
```

If anyone has both jose and jwkest installed together, they are probably broken already.  How about that?

**Comment by juanifioren** [comment]
Mmm sounds good to me. Let's try it. Tomorrow I'll try to update `feature-jwtdeps` branch but if you to send the PR now will be awesome.

**Pull request merged**
