### PR TITLE
Implement Front-Channel Logout (draft 01)

### PR DESCRIPTION
**Pull request by davidmr**
Hi @juanifioren 

We've started using this oidc-provider inside our company and found it very helpful. However we want to include a way for RP's to logout from the OP and vice versa. We did a little research and found that OpenID is woking in a specification about it. So we've started implementing it and wanted to know what do you think and if it's worth merging it.

Here's a summary of the changes:
* Added fields to the Client model to identify if they support Front-Channel Logout.
* Added a logout signal receiver to store the user that just logged out, so that it is
  available later in the request life cycle (e.g. `logout_clients` templatetag).
* create_token_id now verifies if it should include a session id within the claims.
* Added and refactored some logic regarding token manipulation to avoid code duplication.
* Created the `logout_clients` templatetag to logout RPs from the OP.
* Modified the `logout` view to work according to the spec.
* Proper Logout documentation included.

Thanks in advance.

### CODE REVIEW

**Comment by juanifioren** [comment]
Hi @davidmr. I've read the draft. I'll try to take a look before merging into the stable release branch. Feel free to push more work. Awesome contribution btw! :)

PD: Can you create an issue for this?

**Comment by davidmr** [comment]
I created this issue: https://github.com/juanifioren/django-oidc-provider/issues/120. Let me know if I'm missing something.

**Comment by juanifioren** [comment]
After the user logged out you attach the object in the `request` but then a redirect happens and that `request.user_logged_out` doesn't exist.

screen shot 2016-10-26 at 15 43 04

Am I doing something wrong?

**Comment by davidmr** [comment]
I don't think you are doing anything wrong. I'll take a look at it as soon as I can and let you know what happened.

Thanks!

**Comment by juanifioren** [comment]
I was using example_project app and using /admin/logout/ view.

**Comment by juanifioren** [comment]
And using branch `feature-frontchannel-logout` merged with `v0.4.x`.

**Comment by davidmr** [comment]
@juanifioren Do you happen to have the actual code you used when the error showed up? (I haven't been able to reproduce it)

**Comment by juanifioren** [comment]
I use [feature-frontchannel-logout](https://github.com/juanifioren/django-oidc-provider/tree/feature-frontchannel-logout) branch. Maybe I'm missing something? Which are the steps for setup?.

**Comment by davidmr** [comment]
It actually depends on what you want to try. If you are testing logging out from the OP so that the RP logout too, you need to register the `frontchannel_logout_uri` property in the `Client` and them include the `logout_clients` tag in the page show after logout. If you are testing logging out from the RP so that the OP logout too, you need to configure the RP to issue a request to `end_session_endpoint`.

I don't know if that answers your question, let me know if it doesn't 👍

**Comment by juanifioren** [comment]
I just hit `/admin/logout/`.

**Comment by davidmr** [comment]
@juanifioren I haven't been able to reproduce it. Here's what I'm doing: http://g.recordit.co/yOERpSDtac.gif

**Comment by juanifioren** [comment]
Ok. Try this url `/admin/logout/?next=/` please

**Comment by davidmr** [comment]
Sorry for the late reply. I haven't been able to come back to this, I'll let you know as soon as I can.

**Comment by davidmr** [comment]
@juanifioren I managed to reproduce the issue and fix it (I think). 

I've rebased and updated our branch at https://github.com/torreco/django-oidc-provider/tree/feature-frontchannel-logout with the head of `v.0.4.x`.

**Comment by davidmr** [comment]
@juanifioren Did you have a chance to take a look at this?

**Pull request merged**
