### PR TITLE
JWT deps support for pyjwkest and python-jose

### PR DESCRIPTION
**Pull request by jdunck**
I haven't been able to keep requirements-file compat.  That is, install with pyjwkest is now 'pip install django-oidc-provider[pyjwkest]' rather than 'pip install django-oidc-provider'.  Otherwise, this PR has tests passing in all tox environments (have a look at diff in setup.py and tox.ini).

Given the change in install, I think maybe this would make 0.4.0?  Feedback welcome. :)

### CODE REVIEW

**Comment by jdunck** [comment]
Well, not all tox envs, let me shake out some bugs.

**Comment by jdunck** [comment]
On stock v0.3.x, under django 1.9, I am seeing failures such as:

```python
ERROR: test_response (oidc_provider.tests.test_provider_info_endpoint.ProviderInfoTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jdunck/consulting/matterport/src/django-oidc-provider/oidc_provider/tests/test_provider_info_endpoint.py", line 18, in test_response
    url = reverse('oidc_provider:provider_info')
  File "/Users/jdunck/consulting/matterport/src/django-oidc-provider/.tox/py27-django19/lib/python2.7/site-packages/django/urls/base.py", line 89, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
NoReverseMatch: u'en-us' is not a registered namespace
```

I tracked it down to the fact that tox.ini for 1.9 said to install <2.0, but of course there is now 1.10, which has breaking changes for this project.  I'll do a separate PR to fix that.

**Comment by jdunck** [comment]
```bash
  py27-django17-jwkest: commands succeeded
  py27-django17-jose: commands succeeded
  py27-django18-jwkest: commands succeeded
  py27-django18-jose: commands succeeded
  py27-django19-jwkest: commands succeeded
  py27-django19-jose: commands succeeded
```

Fails on 3.4 and 3.5 locally due to local version issues (unrelated to this PR).

**Comment by juanifioren** [comment]
I'll be testing this today. Thanks.

**Comment by juanifioren** [comment]
@jdunck master is stable. I created a branch for this called [feature-jwtdeps](https://github.com/juanifioren/django-oidc-provider/tree/feature-jwtdeps). Could you please make a pull request into that branch?. Sorry for this. Thanks.

**Comment by jdunck** [comment]
Sure, I can.  Can you push latest v0.3.x to the feature branch?

**Comment by juanifioren** [comment]
Ready!

**Pull request closed without merging**
